service: serverless-graphql

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  playground:
    handler: src/index.handler
    events:
      - http:
          path: playground
          method: get

  graphql:
    handler: src/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
